name: Check TFL Line Status

on:
  workflow_dispatch:
  schedule:
    - cron: '30 6 * * 1-5'  # Runs at 07:30 AM (Monday to Friday)
    - cron: '00 7 * * 1-5'  # Runs at 08:00 AM (Monday to Friday)
    - cron: '30 15 * * 1-5' # Runs at 04:30 PM (Monday to Friday)
    - cron: '00 16 * * 1-5' # Runs at 05:00 PM (Monday to Friday)

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0

      - name: Cache previous disruptions
        uses: actions/cache@v3
        id: cache
        with:
          path: previous_disruptions.json
          key: ${{ runner.os }}-previous-disruptions
          restore-keys: |
            ${{ runner.os }}-previous-disruptions-

      - name: Create empty previous disruptions file if not cached
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo '[]' > previous_disruptions.json

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node checkTfl.js
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}

      - name: Save previous disruptions to cache
        uses: actions/cache/save@v3
        if: always() && (github.event_name != 'schedule' || (github.event.schedule != '0 7 * * 1-5' && github.event.schedule != '0 16 * * 1-5'))
        with:
          path: previous_disruptions.json
          key: ${{ runner.os }}-previous-disruptions

      - name: Delete cache for specific runs
        if: github.event_name == 'schedule' && (github.event.schedule == '0 7 * * 1-5' || github.event.schedule == '0 16 * * 1-5')
        run: |
          echo "Installing GitHub CLI..."
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

          echo "Fetching cache key..."
          CACHE_KEY="${{ runner.os }}-previous-disruptions"
          echo "Deleting cache for key: $CACHE_KEY"
          
          # List and delete all caches matching our key
          gh cache list --key "$CACHE_KEY" --json id --jq '.[].id' | while read -r cache_id; do
            echo "Deleting cache ID: $cache_id"
            gh cache delete "$cache_id"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}

