name: Check TFL Line Status

on:
  workflow_dispatch:
  schedule:
    - cron: '30 6 * * 1-5'  # Runs at 07:30 AM (Monday to Friday)
    - cron: '00 7 * * 1-5'  # Runs at 08:0 AM (Monday to Friday)
    - cron: '30 15 * * 1-5' # Runs at 04:30 PM (Monday to Friday)
    - cron: '00 16 * * 1-5' # Runs at 05:00 PM (Monday to Friday)

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0

      - name: Download previous disruptions
        uses: actions/download-artifact@main
        with:
          name: previous-disruptions
          path: previous_disruptions.json
          if-no-files-found: ignore

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node checkTfl.js
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}

      - name: Upload previous disruptions
        uses: actions/upload-artifact@main
        with:
          name: previous-disruptions
          path: previous_disruptions.json
          if-no-files-found: ignore
          retention-days: 1

